collect hub backup and restore resources
stolostron/must-gather pull request #83
Opened 2022-02-11 20:45 UTC by birsanv

Signed-off-by: Valentina Birsan <vbirsan@redhat.com>

**Related Issue:**  https://github.com/stolostron/backlog/issues/19750

**Description of Changes:**

**What resource is being added**: 
- restores.cluster.open-cluster-management.io
- backupschedules.cluster.open-cluster-management.io
- backupstoragelocations.velero.io
- backups.velero.io
- restores.velero.io

**Is this a Hub or Managed cluster change?:**  HUB
Hub Cluster | Managed Cluster

**Notes:**

2022-02-12 00:56 UTC, ycao56 requested changes

2022-02-12 00:56 UTC, ycao56 commented on collection-scripts/gather
> +    oc adm inspect restores.cluster.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
Wrong place. If these are the resources on the hub, it should be in the section on line 84 below. 
```
case "$CLUSTER" in 
    #case 1 
"HUB")
```

2022-02-12 15:08 UTC, birsanv commented on collection-scripts/gather
> +    oc adm inspect restores.cluster.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
fixed, thanks

2022-02-14 18:10 UTC, jlpadilla approved these changes
/lgtm

2022-02-14 18:10 UTC, merged